/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', '"SF Pro Text"', '"Helvetica Neue"', 'Helvetica', 'Arial', 'sans-serif'],
      },
      colors: {
        'warm-orange': '#FF7F32',
        'warm-orange-dark': '#E86A1E',
        'warm-orange-light': '#FFB088',
        'cream-white': '#FFF9F3',
        'light-beige': '#F5EFE6',
        'coffee': '#E8DFD5',
        'brick-red': '#D85A38',
        'brick-red-dark': '#C04A2A',
        'warm-gray': '#8B7E74',
        'warm-gray-light': '#B0A59C',
        'warm-gray-dark': '#6B5E54',
        'ios-bg': '#FFF9F3',
        'ios-card': '#FFFFFF',
        'ios-text': '#3D3429',
        'ios-text-secondary': '#8B7E74',
        'ios-blue': '#FF7F32',
        'ios-green': '#4CAF50',
        'ios-orange': '#FF7F32',
        'ios-red': '#D85A38',
        'ios-pink': '#FF2D55',
        'ios-purple': '#AF52DE',
        'ios-teal': '#5AC8FA',
        'ios-yellow': '#FFCC00',
        'ios-gray': '#8B7E74',
        'ios-gray-2': '#B0A59C',
        'ios-gray-3': '#C7C7CC',
        'ios-gray-4': '#D1D1D6',
        'ios-gray-5': '#E8DFD5',
        'ios-gray-6': '#F5EFE6',
        // 品级配色
        'gacha-gold': '#FFD700',
        'gacha-gold-dark': '#FFA500',
        'gacha-gold-light': '#FFEC8B',
        'gacha-silver': '#C0C0C0',
        'gacha-silver-dark': '#A8A8A8',
        'gacha-silver-light': '#E8E8E8',
        'gacha-bronze': '#CD7F32',
        'gacha-bronze-dark': '#8B5A2B',
        'gacha-bronze-light': '#E8A862',
      },
      borderRadius: {
        'ios': '20px',
        'ios-lg': '24px',
        'ios-sm': '16px',
        'ios-xs': '12px',
      },
      boxShadow: {
        'ios': '0 4px 24px rgba(0, 0, 0, 0.08)',
        'ios-hover': '0 12px 40px rgba(0, 0, 0, 0.15)',
        'ios-inner': 'inset 0 1px 2px rgba(255, 255, 255, 0.8), inset 0 -1px 2px rgba(0, 0, 0, 0.05)',
        'ios-button': '0 2px 8px rgba(0, 122, 255, 0.3)',
        'gacha-gold': '0 0 20px rgba(255, 215, 0, 0.5)',
        'gacha-silver': '0 0 15px rgba(192, 192, 192, 0.4)',
        'gacha-bronze': '0 0 10px rgba(205, 127, 50, 0.3)',
      },
      transitionTimingFunction: {
        'ios': 'cubic-bezier(0.4, 0.0, 0.2, 1)',
        'ios-spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      animation: {
        'shimmer': 'shimmer 3s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'pulse-soft': 'pulse-soft 2s ease-in-infinite',
        'gacha-glow': 'gacha-glow 2s ease-in-out infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { transform: 'translateX(-100%) rotate(25deg)' },
          '100%': { transform: 'translateX(200%) rotate(25deg)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        'gacha-glow': {
          '0%, 100%': { boxShadow: '0 0 15px rgba(255, 215, 0, 0.3)' },
          '50%': { boxShadow: '0 0 30px rgba(255, 215, 0, 0.6)' },
        },
      },
    },
  },
  plugins: [],
}
